[package]
name = "rust_vss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
num-primes = "0.3.0"
num-bigint = { version = "0.2.6", features = ["rand"] }
rand = "0.5.6"
